# Generated by Django 4.1.7 on 2023-04-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=500, null=True, verbose_name='ФИО')),
                ('password_user', models.CharField(max_length=100, null=True, verbose_name='Пароль')),
                ('mail_user', models.CharField(max_length=100, null=True, verbose_name='Почта')),
                ('class_user', models.BooleanField(null=True)),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
