# Generated by Django 4.1.7 on 2023-04-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='')),
                ('age', models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('18+', '18+')], max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=100, null=True, verbose_name='')),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Мероприятия',
                'verbose_name_plural': 'мероприятия',
            },
        ),
    ]
