# Generated by Django 4.1.7 on 2023-04-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_ticket_remove_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image_ticket',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name_ticket',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
    ]
