# Generated by Django 4.1.7 on 2023-04-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0007_event_buration_alter_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='buration',
            field=models.IntegerField(max_length=100, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(null=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_event',
            field=models.TextField(max_length=1000, null=True, verbose_name='Краткое описание'),
        ),
    ]
