# Generated by Django 4.1.7 on 2023-04-19 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0008_alter_event_buration_alter_event_date_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='email',
            new_name='email_organizer',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='number_phone',
            new_name='number_phone_organizer',
        ),
        migrations.AddField(
            model_name='event',
            name='mini_description_event',
            field=models.TextField(max_length=1000, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='participants',
            name='email_participants',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='participants',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizer.event', verbose_name='Мероприятие'),
        ),
        migrations.AddField(
            model_name='participants',
            name='number_phone_participants',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_event',
            field=models.TextField(max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizer.organization', verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='age_participants',
            field=models.IntegerField(null=True, verbose_name='Возрост'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='name_participants',
            field=models.CharField(max_length=100, null=True, verbose_name='ФИО'),
        ),
    ]
