# Generated by Django 4.2 on 2023-04-20 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0009_rename_email_organization_email_organizer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организаторы', 'verbose_name_plural': 'Организаторы'},
        ),
        migrations.AlterModelOptions(
            name='participants',
            options={'verbose_name': 'Участники', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='email_participants',
            field=models.EmailField(max_length=254, null=True, verbose_name='Почта участника'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='name_participants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizer.participants', verbose_name='Имя участника'),
        ),
        migrations.AlterField(
            model_name='event',
            name='buration',
            field=models.IntegerField(null=True, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='event',
            name='mini_description_event',
            field=models.TextField(max_length=100, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email_organizer',
            field=models.EmailField(max_length=254, null=True, verbose_name='Почта организатора'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='number_phone_organizer',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер организатора'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='email_participants',
            field=models.EmailField(max_length=254, null=True, verbose_name='Почта участника'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='number_phone_participants',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер участника'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price_ticket',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
    ]
