# Generated by Django 4.1.7 on 2023-04-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0009_rename_email_organization_email_organizer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организаторы', 'verbose_name_plural': 'Организаторы'},
        ),
        migrations.AlterModelOptions(
            name='participants',
            options={'verbose_name': 'Участники', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterField(
            model_name='event',
            name='buration',
            field=models.IntegerField(null=True, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='event',
            name='mini_description_event',
            field=models.TextField(max_length=100, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price_ticket',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
    ]
